### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by emmaLP** [aws/aws-secretsmanager-caching-go#22]
This repo is currently recommended in the [aws secret retrieval docs](https://docs.aws.amazon.com/secretsmanager/latest/userguide/retrieving-secrets_cache-go.html) but the aws sdk is out of date and there have been no active development since 2019

**Comment by jbct** [comment]
Hi emmaLP. Yes, the project is still active. Is there a particular issue that you're encountering? We've intentionally chosen to defer upgrading the AWS SDK at this time because SDK v1 is still supported (https://docs.aws.amazon.com/sdkref/latest/guide/version-support-matrix.html) and compatible with SDK v2 projects.

**Comment by emmaLP** [comment]
Hi @jbct 

That's great news to hear that this is still active. 

Not experiencing any particular issue; my team and I were looking to make this repo our standard for looking up secrets but were apprehensive since they main functionality hadn't changed since 2019 and the aws sdk v1 was on a rather old version.

Do you have a roapmap of upcoming improvements we can look at please?

**Comment by jbct** [comment]
Unfortunately I don't, but features and enhancements to the library are driven by customer requests. If there's something you want to see, definitely post an issue/enhancement here or discuss with your TAM.
